# To manually build docs locally:
# mkvirtualenv3 pymetrics-docs
# pip install -e .[docs]
# cd docs
# make html
# open _build/html/index.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
